#pragma once

#define FONT_ICON_FILE_NAME_RA "rpgawesome-webfont.ttf"
#define ICON_MIN_RA 0xe900
#define ICON_MAX_RA 0xeaee

#define ICON_RA_ACID "\xee\xa4\x80"	// U+e900
#define ICON_RA_ZIGZAG_LEAF "\xee\xab\xae"	// U+eaee
#define ICON_RA_ARCHER "\xee\xa4\x8d"	// U+e90d
#define ICON_RA_ARCHERY_TARGET "\xee\xa4\x8e"	// U+e90e
#define ICON_RA_ARENA "\xee\xa4\x8f"	// U+e90f
#define ICON_RA_ARIES "\xee\xa4\x90"	// U+e910
#define ICON_RA_ARROW_CLUSTER "\xee\xa4\x91"	// U+e911
#define ICON_RA_ARROW_FLIGHTS "\xee\xa4\x92"	// U+e912
#define ICON_RA_ARSON "\xee\xa4\x93"	// U+e913
#define ICON_RA_AURA "\xee\xa4\x94"	// U+e914
#define ICON_RA_AWARE "\xee\xa4\x95"	// U+e915
#define ICON_RA_AXE "\xee\xa4\x97"	// U+e917
#define ICON_RA_AXE_SWING "\xee\xa4\x96"	// U+e916
#define ICON_RA_BALL "\xee\xa4\x98"	// U+e918
#define ICON_RA_BARBED_ARROW "\xee\xa4\x99"	// U+e919
#define ICON_RA_BARRIER "\xee\xa4\x9a"	// U+e91a
#define ICON_RA_BAT_SWORD "\xee\xa4\x9b"	// U+e91b
#define ICON_RA_BATTERED_AXE "\xee\xa4\x9c"	// U+e91c
#define ICON_RA_BATTERIES "\xee\xa4\x9d"	// U+e91d
#define ICON_RA_BATTERY_0 "\xee\xa4\x9e"	// U+e91e
#define ICON_RA_BATTERY_25 "\xee\xa4\x9f"	// U+e91f
#define ICON_RA_BATTERY_50 "\xee\xa4\xa0"	// U+e920
#define ICON_RA_BATTERY_75 "\xee\xa4\xa1"	// U+e921
#define ICON_RA_BATTERY_100 "\xee\xa4\xa2"	// U+e922
#define ICON_RA_BATTERY_BLACK "\xee\xa4\xa3"	// U+e923
#define ICON_RA_BATTERY_NEGATIVE "\xee\xa4\xa4"	// U+e924
#define ICON_RA_BATTERY_POSITIVE "\xee\xa4\xa5"	// U+e925
#define ICON_RA_BATTERY_WHITE "\xee\xa4\xa6"	// U+e926
#define ICON_RA_BATWINGS "\xee\xa4\xa7"	// U+e927
#define ICON_RA_BEAM_WAKE "\xee\xa4\xa8"	// U+e928
#define ICON_RA_BEAR_TRAP "\xee\xa4\xa9"	// U+e929
#define ICON_RA_BEER "\xee\xa4\xaa"	// U+e92a
#define ICON_RA_BEETLE "\xee\xa4\xab"	// U+e92b
#define ICON_RA_BELL "\xee\xa4\xac"	// U+e92c
#define ICON_RA_BIOHAZARD "\xee\xa4\xad"	// U+e92d
#define ICON_RA_BIRD_CLAW "\xee\xa4\xae"	// U+e92e
#define ICON_RA_BIRD_MASK "\xee\xa4\xaf"	// U+e92f
#define ICON_RA_BLADE_BITE "\xee\xa4\xb0"	// U+e930
#define ICON_RA_BLAST "\xee\xa4\xb1"	// U+e931
#define ICON_RA_BLASTER "\xee\xa4\xb2"	// U+e932
#define ICON_RA_BLEEDING_EYE "\xee\xa4\xb3"	// U+e933
#define ICON_RA_BLEEDING_HEARTS "\xee\xa4\xb4"	// U+e934
#define ICON_RA_BOLT_SHIELD "\xee\xa4\xb5"	// U+e935
#define ICON_RA_BOMB_EXPLOSION "\xee\xa4\xb6"	// U+e936
#define ICON_RA_BOMBS "\xee\xa4\xb7"	// U+e937
#define ICON_RA_BONE_BITE "\xee\xa4\xb8"	// U+e938
#define ICON_RA_BONE_KNIFE "\xee\xa4\xb9"	// U+e939
#define ICON_RA_BOOK "\xee\xa4\xba"	// U+e93a
#define ICON_RA_BOOMERANG "\xee\xa4\xbb"	// U+e93b
#define ICON_RA_BOOT_STOMP "\xee\xa4\xbc"	// U+e93c
#define ICON_RA_BOTTLE_VAPORS "\xee\xa4\xbd"	// U+e93d
#define ICON_RA_BOTTLED_BOLT "\xee\xa4\xbe"	// U+e93e
#define ICON_RA_BOTTOM_RIGHT "\xee\xa4\xbf"	// U+e93f
#define ICON_RA_BOWIE_KNIFE "\xee\xa5\x80"	// U+e940
#define ICON_RA_BOWLING_PIN "\xee\xa5\x81"	// U+e941
#define ICON_RA_BRAIN_FREEZE "\xee\xa5\x82"	// U+e942
#define ICON_RA_BRANDY_BOTTLE "\xee\xa5\x83"	// U+e943
#define ICON_RA_BRIDGE "\xee\xa5\x84"	// U+e944
#define ICON_RA_BROADHEAD_ARROW "\xee\xa5\x85"	// U+e945
#define ICON_RA_BROADSWORD "\xee\xa5\x86"	// U+e946
#define ICON_RA_BROKEN_BONE "\xee\xa5\x87"	// U+e947
#define ICON_RA_BROKEN_BOTTLE "\xee\xa5\x88"	// U+e948
#define ICON_RA_BROKEN_HEART "\xee\xa5\x88"	// U+e948
#define ICON_RA_BROKEN_SHIELD "\xee\xa5\x8a"	// U+e94a
#define ICON_RA_BROKEN_SKULL "\xee\xa5\x8b"	// U+e94b
#define ICON_RA_BUBBLING_POTION "\xee\xa5\x8c"	// U+e94c
#define ICON_RA_BULLETS "\xee\xa5\x8d"	// U+e94d
#define ICON_RA_BURNING_BOOK "\xee\xa5\x8e"	// U+e94e
#define ICON_RA_BURNING_EMBERS "\xee\xa5\x8f"	// U+e94f
#define ICON_RA_BURNING_EYE "\xee\xa5\x90"	// U+e950
#define ICON_RA_BURNING_METEOR "\xee\xa5\x91"	// U+e951
#define ICON_RA_BURST_BLOB "\xee\xa5\x92"	// U+e952
#define ICON_RA_BUTTERFLY "\xee\xa5\x93"	// U+e953
#define ICON_RA_CAMPFIRE "\xee\xa5\x94"	// U+e954
#define ICON_RA_CANCEL "\xee\xa5\x95"	// U+e955
#define ICON_RA_CANCER "\xee\xa5\x96"	// U+e956
#define ICON_RA_CANDLE "\xee\xa5\x98"	// U+e958
#define ICON_RA_CANDLE_FIRE "\xee\xa5\x97"	// U+e957
#define ICON_RA_CANNON_SHOT "\xee\xa5\x99"	// U+e959
#define ICON_RA_CAPITOL "\xee\xa5\x9a"	// U+e95a
#define ICON_RA_CAPRICORN "\xee\xa5\x9b"	// U+e95b
#define ICON_RA_CARROT "\xee\xa5\x9c"	// U+e95c
#define ICON_RA_CASTLE_EMBLEM "\xee\xa5\x9d"	// U+e95d
#define ICON_RA_CASTLE_FLAG "\xee\xa5\x9e"	// U+e95e
#define ICON_RA_CAT "\xee\xa5\x9f"	// U+e95f
#define ICON_RA_CHAIN "\xee\xa5\xa0"	// U+e960
#define ICON_RA_CHEESE "\xee\xa5\xa1"	// U+e961
#define ICON_RA_CHEMICAL_ARROW "\xee\xa5\xa2"	// U+e962
#define ICON_RA_CHESSBOARD "\xee\xa5\xa3"	// U+e963
#define ICON_RA_CHICKEN_LEG "\xee\xa5\xa4"	// U+e964
#define ICON_RA_CIRCLE_OF_CIRCLES "\xee\xa5\xa5"	// U+e965
#define ICON_RA_CIRCULAR_SAW "\xee\xa5\xa6"	// U+e966
#define ICON_RA_CIRCULAR_SHIELD "\xee\xa5\xa7"	// U+e967
#define ICON_RA_CLOAK_AND_DAGGER "\xee\xa5\xa8"	// U+e968
#define ICON_RA_CLOCKWORK "\xee\xa5\xa9"	// U+e969
#define ICON_RA_CLOVER "\xee\xa5\xaa"	// U+e96a
#define ICON_RA_CLOVERS "\xee\xa5\xac"	// U+e96c
#define ICON_RA_CLOVERS_CARD "\xee\xa5\xab"	// U+e96b
#define ICON_RA_CLUSTER_BOMB "\xee\xa5\xad"	// U+e96d
#define ICON_RA_COFFEE_MUG "\xee\xa5\xae"	// U+e96e
#define ICON_RA_COG "\xee\xa5\xb0"	// U+e970
#define ICON_RA_COG_WHEEL "\xee\xa5\xaf"	// U+e96f
#define ICON_RA_COLD_HEART "\xee\xa5\xb1"	// U+e971
#define ICON_RA_COMPASS "\xee\xa5\xb2"	// U+e972
#define ICON_RA_CORKED_TUBE "\xee\xa5\xb3"	// U+e973
#define ICON_RA_CRAB_CLAW "\xee\xa5\xb4"	// U+e974
#define ICON_RA_CRACKED_HELM "\xee\xa5\xb5"	// U+e975
#define ICON_RA_CRACKED_SHIELD "\xee\xa5\xb6"	// U+e976
#define ICON_RA_CROC_SWORD "\xee\xa5\xb7"	// U+e977
#define ICON_RA_CROSSBOW "\xee\xa5\xb8"	// U+e978
#define ICON_RA_CROSSED_AXES "\xee\xa5\xb9"	// U+e979
#define ICON_RA_CROSSED_BONES "\xee\xa5\xba"	// U+e97a
#define ICON_RA_CROSSED_PISTOLS "\xee\xa5\xbb"	// U+e97b
#define ICON_RA_CROSSED_SABRES "\xee\xa5\xbc"	// U+e97c
#define ICON_RA_CROSSED_SWORDS "\xee\xa5\xbd"	// U+e97d
#define ICON_RA_CROWN "\xee\xa5\xbf"	// U+e97f
#define ICON_RA_CROWN_OF_THORNS "\xee\xa5\xbe"	// U+e97e
#define ICON_RA_CROWNED_HEART "\xee\xa6\x80"	// U+e980
#define ICON_RA_CRUSH "\xee\xa6\x81"	// U+e981
#define ICON_RA_CRYSTAL_BALL "\xee\xa6\x82"	// U+e982
#define ICON_RA_CRYSTAL_CLUSTER "\xee\xa6\x83"	// U+e983
#define ICON_RA_CRYSTAL_WAND "\xee\xa6\x84"	// U+e984
#define ICON_RA_CRYSTALS "\xee\xa6\x85"	// U+e985
#define ICON_RA_CUBES "\xee\xa6\x86"	// U+e986
#define ICON_RA_CUT_PALM "\xee\xa6\x87"	// U+e987
#define ICON_RA_CYCLE "\xee\xa6\x88"	// U+e988
#define ICON_RA_DAGGERS "\xee\xa6\x89"	// U+e989
#define ICON_RA_DAISY "\xee\xa6\x8a"	// U+e98a
#define ICON_RA_DEAD_TREE "\xee\xa6\x8b"	// U+e98b
#define ICON_RA_DEATH_SKULL "\xee\xa6\x8c"	// U+e98c
#define ICON_RA_DECAPITATION "\xee\xa6\x8d"	// U+e98d
#define ICON_RA_DEFIBRILLATE "\xee\xa6\x8e"	// U+e98e
#define ICON_RA_DEMOLISH "\xee\xa6\x8f"	// U+e98f
#define ICON_RA_DERVISH_SWORDS "\xee\xa6\x90"	// U+e990
#define ICON_RA_DESERT_SKULL "\xee\xa6\x91"	// U+e991
#define ICON_RA_DIAMOND "\xee\xa6\x92"	// U+e992
#define ICON_RA_DIAMONDS "\xee\xa6\x94"	// U+e994
#define ICON_RA_DIAMONDS_CARD "\xee\xa6\x93"	// U+e993
#define ICON_RA_DICE_FIVE "\xee\xa6\x95"	// U+e995
#define ICON_RA_DICE_FOUR "\xee\xa6\x96"	// U+e996
#define ICON_RA_DICE_ONE "\xee\xa6\x97"	// U+e997
#define ICON_RA_DICE_SIX "\xee\xa6\x98"	// U+e998
#define ICON_RA_DICE_THREE "\xee\xa6\x99"	// U+e999
#define ICON_RA_DICE_TWO "\xee\xa6\x9a"	// U+e99a
#define ICON_RA_DINOSAUR "\xee\xa6\x9b"	// U+e99b
#define ICON_RA_DIVERT "\xee\xa6\x9c"	// U+e99c
#define ICON_RA_DIVING_DAGGER "\xee\xa6\x9d"	// U+e99d
#define ICON_RA_DOUBLE_TEAM "\xee\xa6\x9e"	// U+e99e
#define ICON_RA_DOUBLED "\xee\xa6\x9f"	// U+e99f
#define ICON_RA_DRAGON "\xee\xa6\xa2"	// U+e9a2
#define ICON_RA_DRAGON_BREATH "\xee\xa6\xa0"	// U+e9a0
#define ICON_RA_DRAGON_WING "\xee\xa6\xa1"	// U+e9a1
#define ICON_RA_DRAGONFLY "\xee\xa6\xa3"	// U+e9a3
#define ICON_RA_DRILL "\xee\xa6\xa4"	// U+e9a4
#define ICON_RA_DRIPPING_BLADE "\xee\xa6\xa5"	// U+e9a5
#define ICON_RA_DRIPPING_KNIFE "\xee\xa6\xa6"	// U+e9a6
#define ICON_RA_DRIPPING_SWORD "\xee\xa6\xa7"	// U+e9a7
#define ICON_RA_DROPLET "\xee\xa6\xa9"	// U+e9a9
#define ICON_RA_DROPLET_SPLASH "\xee\xa6\xa8"	// U+e9a8
#define ICON_RA_DROPLETS "\xee\xa6\xaa"	// U+e9aa
#define ICON_RA_DUEL "\xee\xa6\xab"	// U+e9ab
#define ICON_RA_EGG "\xee\xa6\xad"	// U+e9ad
#define ICON_RA_EGG_POD "\xee\xa6\xac"	// U+e9ac
#define ICON_RA_EGGPLANT "\xee\xa6\xae"	// U+e9ae
#define ICON_RA_EMERALD "\xee\xa6\xaf"	// U+e9af
#define ICON_RA_ENERGISE "\xee\xa6\xb0"	// U+e9b0
#define ICON_RA_EXPLOSION "\xee\xa6\xb1"	// U+e9b1
#define ICON_RA_EXPLOSIVE_MATERIALS "\xee\xa6\xb2"	// U+e9b2
#define ICON_RA_EYE_MONSTER "\xee\xa6\xb3"	// U+e9b3
#define ICON_RA_EYE_SHIELD "\xee\xa6\xb4"	// U+e9b4
#define ICON_RA_EYEBALL "\xee\xa6\xb5"	// U+e9b5
#define ICON_RA_FAIRY "\xee\xa6\xb7"	// U+e9b7
#define ICON_RA_FAIRY_WAND "\xee\xa6\xb6"	// U+e9b6
#define ICON_RA_FALL_DOWN "\xee\xa6\xb8"	// U+e9b8
#define ICON_RA_FALLING "\xee\xa6\xb9"	// U+e9b9
#define ICON_RA_FAST_SHIP "\xee\xa6\xba"	// U+e9ba
#define ICON_RA_FEATHER_WING "\xee\xa6\xbb"	// U+e9bb
#define ICON_RA_FEATHERED_WING "\xee\xa6\xbc"	// U+e9bc
#define ICON_RA_FEDORA "\xee\xa6\xbd"	// U+e9bd
#define ICON_RA_FIRE "\xee\xa7\x83"	// U+e9c3
#define ICON_RA_FIRE_BOMB "\xee\xa6\xbe"	// U+e9be
#define ICON_RA_FIRE_BREATH "\xee\xa6\xbf"	// U+e9bf
#define ICON_RA_FIRE_RING "\xee\xa7\x80"	// U+e9c0
#define ICON_RA_FIRE_SHIELD "\xee\xa7\x81"	// U+e9c1
#define ICON_RA_FIRE_SYMBOL "\xee\xa7\x82"	// U+e9c2
#define ICON_RA_FIREBALL_SWORD "\xee\xa7\x84"	// U+e9c4
#define ICON_RA_FISH "\xee\xa7\x85"	// U+e9c5
#define ICON_RA_FIZZING_FLASK "\xee\xa7\x86"	// U+e9c6
#define ICON_RA_FLAME_SYMBOL "\xee\xa7\x87"	// U+e9c7
#define ICON_RA_FLAMING_ARROW "\xee\xa7\x88"	// U+e9c8
#define ICON_RA_FLAMING_CLAW "\xee\xa7\x89"	// U+e9c9
#define ICON_RA_FLAMING_TRIDENT "\xee\xa7\x8a"	// U+e9ca
#define ICON_RA_FLASK "\xee\xa7\x8b"	// U+e9cb
#define ICON_RA_FLAT_HAMMER "\xee\xa7\x8c"	// U+e9cc
#define ICON_RA_FLOWER "\xee\xa7\x8d"	// U+e9cd
#define ICON_RA_FLOWERS "\xee\xa7\x8e"	// U+e9ce
#define ICON_RA_FLUFFY_SWIRL "\xee\xa7\x8f"	// U+e9cf
#define ICON_RA_FOCUSED_LIGHTNING "\xee\xa7\x90"	// U+e9d0
#define ICON_RA_FOOD_CHAIN "\xee\xa7\x91"	// U+e9d1
#define ICON_RA_FOOTPRINT "\xee\xa7\x92"	// U+e9d2
#define ICON_RA_FORGING "\xee\xa7\x93"	// U+e9d3
#define ICON_RA_FORWARD "\xee\xa7\x94"	// U+e9d4
#define ICON_RA_FOX "\xee\xa7\x95"	// U+e9d5
#define ICON_RA_FROST_EMBLEM "\xee\xa7\x96"	// U+e9d6
#define ICON_RA_FROSTFIRE "\xee\xa7\x97"	// U+e9d7
#define ICON_RA_FROZEN_ARROW "\xee\xa7\x98"	// U+e9d8
#define ICON_RA_GAMEPAD_CROSS "\xee\xa7\x99"	// U+e9d9
#define ICON_RA_GAVEL "\xee\xa7\x9a"	// U+e9da
#define ICON_RA_GEAR_HAMMER "\xee\xa7\x9b"	// U+e9db
#define ICON_RA_GEAR_HEART "\xee\xa7\x9c"	// U+e9dc
#define ICON_RA_GEARS "\xee\xa7\x9d"	// U+e9dd
#define ICON_RA_GECKO "\xee\xa7\x9e"	// U+e9de
#define ICON_RA_GEM "\xee\xa7\xa0"	// U+e9e0
#define ICON_RA_GEM_PENDANT "\xee\xa7\x9f"	// U+e9df
#define ICON_RA_GEMINI "\xee\xa7\xa1"	// U+e9e1
#define ICON_RA_GLASS_HEART "\xee\xa7\xa2"	// U+e9e2
#define ICON_RA_GLOOP "\xee\xa7\xa3"	// U+e9e3
#define ICON_RA_GOLD_BAR "\xee\xa7\xa4"	// U+e9e4
#define ICON_RA_GRAPPLING_HOOK "\xee\xa7\xa5"	// U+e9e5
#define ICON_RA_GRASS "\xee\xa7\xa7"	// U+e9e7
#define ICON_RA_GRASS_PATCH "\xee\xa7\xa6"	// U+e9e6
#define ICON_RA_GRENADE "\xee\xa7\xa8"	// U+e9e8
#define ICON_RA_GROUNDBREAKER "\xee\xa7\xa9"	// U+e9e9
#define ICON_RA_GUARDED_TOWER "\xee\xa7\xaa"	// U+e9ea
#define ICON_RA_GUILLOTINE "\xee\xa7\xab"	// U+e9eb
#define ICON_RA_HALBERD "\xee\xa7\xac"	// U+e9ec
#define ICON_RA_HAMMER "\xee\xa7\xae"	// U+e9ee
#define ICON_RA_HAMMER_DROP "\xee\xa7\xad"	// U+e9ed
#define ICON_RA_HAND "\xee\xa7\xb1"	// U+e9f1
#define ICON_RA_HAND_EMBLEM "\xee\xa7\xaf"	// U+e9ef
#define ICON_RA_HAND_SAW "\xee\xa7\xb0"	// U+e9f0
#define ICON_RA_HARPOON_TRIDENT "\xee\xa7\xb2"	// U+e9f2
#define ICON_RA_HEALTH "\xee\xa7\xb5"	// U+e9f5
#define ICON_RA_HEALTH_DECREASE "\xee\xa7\xb3"	// U+e9f3
#define ICON_RA_HEALTH_INCREASE "\xee\xa7\xb4"	// U+e9f4
#define ICON_RA_HEART_BOTTLE "\xee\xa7\xb6"	// U+e9f6
#define ICON_RA_HEART_TOWER "\xee\xa7\xb7"	// U+e9f7
#define ICON_RA_HEARTBURN "\xee\xa7\xb8"	// U+e9f8
#define ICON_RA_HEARTS "\xee\xa7\xba"	// U+e9fa
#define ICON_RA_HEARTS_CARD "\xee\xa7\xb9"	// U+e9f9
#define ICON_RA_HEAT_HAZE "\xee\xa7\xbb"	// U+e9fb
#define ICON_RA_HEAVY_FALL "\xee\xa7\xbc"	// U+e9fc
#define ICON_RA_HEAVY_SHIELD "\xee\xa7\xbd"	// U+e9fd
#define ICON_RA_HELMET "\xee\xa7\xbe"	// U+e9fe
#define ICON_RA_HELP "\xee\xa7\xbf"	// U+e9ff
#define ICON_RA_HIVE_EMBLEM "\xee\xa8\x80"	// U+ea00
#define ICON_RA_HOLE_LADDER "\xee\xa8\x81"	// U+ea01
#define ICON_RA_HONEYCOMB "\xee\xa8\x82"	// U+ea02
#define ICON_RA_HOOD "\xee\xa8\x83"	// U+ea03
#define ICON_RA_HORN_CALL "\xee\xa8\x84"	// U+ea04
#define ICON_RA_HORNS "\xee\xa8\x85"	// U+ea05
#define ICON_RA_HORSESHOE "\xee\xa8\x86"	// U+ea06
#define ICON_RA_HOSPITAL_CROSS "\xee\xa8\x87"	// U+ea07
#define ICON_RA_HOT_SURFACE "\xee\xa8\x88"	// U+ea08
#define ICON_RA_HOURGLASS "\xee\xa8\x89"	// U+ea09
#define ICON_RA_HYDRA "\xee\xa8\x8b"	// U+ea0b
#define ICON_RA_HYDSHOT "\xee\xa8\x8a"	// U+ea0a
#define ICON_RA_ICE_CUBE "\xee\xa8\x8c"	// U+ea0c
#define ICON_RA_IMPLOSION "\xee\xa8\x8d"	// U+ea0d
#define ICON_RA_INCENSE "\xee\xa8\x8e"	// U+ea0e
#define ICON_RA_INSECT_JAWS "\xee\xa8\x8f"	// U+ea0f
#define ICON_RA_INTERDICTION "\xee\xa8\x90"	// U+ea10
#define ICON_RA_JETPACK "\xee\xa8\x91"	// U+ea11
#define ICON_RA_JIGSAW_PIECE "\xee\xa8\x92"	// U+ea12
#define ICON_RA_KALEIDOSCOPE "\xee\xa8\x93"	// U+ea13
#define ICON_RA_KETTLEBELL "\xee\xa8\x94"	// U+ea14
#define ICON_RA_KEY "\xee\xa8\x96"	// U+ea16
#define ICON_RA_KEY_BASIC "\xee\xa8\x95"	// U+ea15
#define ICON_RA_KITCHEN_KNIVES "\xee\xa8\x97"	// U+ea17
#define ICON_RA_KNIFE "\xee\xa8\x99"	// U+ea19
#define ICON_RA_KNIFE_FORK "\xee\xa8\x98"	// U+ea18
#define ICON_RA_KNIGHT_HELMET "\xee\xa8\x9a"	// U+ea1a
#define ICON_RA_KUNAI "\xee\xa8\x9b"	// U+ea1b
#define ICON_RA_LANTERN_FLAME "\xee\xa8\x9c"	// U+ea1c
#define ICON_RA_LARGE_HAMMER "\xee\xa8\x9d"	// U+ea1d
#define ICON_RA_LASER_BLAST "\xee\xa8\x9e"	// U+ea1e
#define ICON_RA_LASER_SITE "\xee\xa8\x9f"	// U+ea1f
#define ICON_RA_LAVA "\xee\xa8\xa0"	// U+ea20
#define ICON_RA_LEAF "\xee\xa8\xa1"	// U+ea21
#define ICON_RA_LEO "\xee\xa8\xa2"	// U+ea22
#define ICON_RA_LEVEL_FOUR "\xee\xa8\xa4"	// U+ea24
#define ICON_RA_LEVEL_FOUR_ADVANCED "\xee\xa8\xa3"	// U+ea23
#define ICON_RA_LEVEL_THREE "\xee\xa8\xa6"	// U+ea26
#define ICON_RA_LEVEL_THREE_ADVANCED "\xee\xa8\xa5"	// U+ea25
#define ICON_RA_LEVEL_TWO "\xee\xa8\xa8"	// U+ea28
#define ICON_RA_LEVEL_TWO_ADVANCED "\xee\xa8\xa7"	// U+ea27
#define ICON_RA_LEVER "\xee\xa8\xa9"	// U+ea29
#define ICON_RA_LIBRA "\xee\xa8\xaa"	// U+ea2a
#define ICON_RA_LIGHT_BULB "\xee\xa8\xab"	// U+ea2b
#define ICON_RA_LIGHTHOUSE "\xee\xa8\xac"	// U+ea2c
#define ICON_RA_LIGHTNING "\xee\xa8\xb1"	// U+ea31
#define ICON_RA_LIGHTNING_BOLT "\xee\xa8\xad"	// U+ea2d
#define ICON_RA_LIGHTNING_STORM "\xee\xa8\xae"	// U+ea2e
#define ICON_RA_LIGHTNING_SWORD "\xee\xa8\xaf"	// U+ea2f
#define ICON_RA_LIGHTNING_TRIO "\xee\xa8\xb0"	// U+ea30
#define ICON_RA_LION "\xee\xa8\xb2"	// U+ea32
#define ICON_RA_LIT_CANDELABRA "\xee\xa8\xb3"	// U+ea33
#define ICON_RA_LOAD "\xee\xa8\xb4"	// U+ea34
#define ICON_RA_LOCKED_FORTRESS "\xee\xa8\xb5"	// U+ea35
#define ICON_RA_LOVE_HOWL "\xee\xa8\xb6"	// U+ea36
#define ICON_RA_MAGGOT "\xee\xa8\xb7"	// U+ea37
#define ICON_RA_MAGNET "\xee\xa8\xb8"	// U+ea38
#define ICON_RA_MASS_DRIVER "\xee\xa8\xb9"	// U+ea39
#define ICON_RA_MATCH "\xee\xa8\xba"	// U+ea3a
#define ICON_RA_MEAT "\xee\xa8\xbc"	// U+ea3c
#define ICON_RA_MEAT_HOOK "\xee\xa8\xbb"	// U+ea3b
#define ICON_RA_MEDICAL_PACK "\xee\xa8\xbd"	// U+ea3d
#define ICON_RA_METAL_GATE "\xee\xa8\xbe"	// U+ea3e
#define ICON_RA_MICROPHONE "\xee\xa8\xbf"	// U+ea3f
#define ICON_RA_MINE_WAGON "\xee\xa9\x80"	// U+ea40
#define ICON_RA_MINING_DIAMONDS "\xee\xa9\x81"	// U+ea41
#define ICON_RA_MIRROR "\xee\xa9\x82"	// U+ea42
#define ICON_RA_MONSTER_SKULL "\xee\xa9\x83"	// U+ea43
#define ICON_RA_MOUNTAINS "\xee\xa9\x84"	// U+ea44
#define ICON_RA_MOON_SUN "\xee\xa9\x85"	// U+ea45
#define ICON_RA_MP5 "\xee\xa9\x86"	// U+ea46
#define ICON_RA_MUSCLE_FAT "\xee\xa9\x87"	// U+ea47
#define ICON_RA_MUSCLE_UP "\xee\xa9\x88"	// U+ea48
#define ICON_RA_MUSKET "\xee\xa9\x89"	// U+ea49
#define ICON_RA_NAILS "\xee\xa9\x8a"	// U+ea4a
#define ICON_RA_NODULAR "\xee\xa9\x8b"	// U+ea4b
#define ICON_RA_NOOSE "\xee\xa9\x8c"	// U+ea4c
#define ICON_RA_NUCLEAR "\xee\xa9\x8d"	// U+ea4d
#define ICON_RA_OCARINA "\xee\xa9\x8e"	// U+ea4e
#define ICON_RA_OCEAN_EMBLEM "\xee\xa9\x8f"	// U+ea4f
#define ICON_RA_OCTOPUS "\xee\xa9\x90"	// U+ea50
#define ICON_RA_OMEGA "\xee\xa9\x91"	// U+ea51
#define ICON_RA_ON_TARGET "\xee\xa9\x92"	// U+ea52
#define ICON_RA_OPHIUCHUS "\xee\xa9\x93"	// U+ea53
#define ICON_RA_OVERHEAD "\xee\xa9\x94"	// U+ea54
#define ICON_RA_OVERMIND "\xee\xa9\x95"	// U+ea55
#define ICON_RA_PALM_TREE "\xee\xa9\x96"	// U+ea56
#define ICON_RA_PAWN "\xee\xa9\x97"	// U+ea57
#define ICON_RA_PAWPRINT "\xee\xa9\x98"	// U+ea58
#define ICON_RA_PERSPECTIVE_DICE_FIVE "\xee\xa9\x99"	// U+ea59
#define ICON_RA_PERSPECTIVE_DICE_FOUR "\xee\xa9\x9a"	// U+ea5a
#define ICON_RA_PERSPECTIVE_DICE_ONE "\xee\xa9\x9b"	// U+ea5b
#define ICON_RA_PERSPECTIVE_DICE_RANDOM "\xee\xa9\x9c"	// U+ea5c
#define ICON_RA_PERSPECTIVE_DICE_SIX "\xee\xa9\x9e"	// U+ea5e
#define ICON_RA_PERSPECTIVE_DICE_TWO "\xee\xa9\x9d"	// U+ea5d
#define ICON_RA_PERSPECTIVE_DICE_THREE "\xee\xa9\x9f"	// U+ea5f
#define ICON_RA_PILL "\xee\xa9\xa0"	// U+ea60
#define ICON_RA_PILLS "\xee\xa9\xa1"	// U+ea61
#define ICON_RA_PINE_TREE "\xee\xa9\xa2"	// U+ea62
#define ICON_RA_PING_PONG "\xee\xa9\xa3"	// U+ea63
#define ICON_RA_PISCES "\xee\xa9\xa4"	// U+ea64
#define ICON_RA_PLAIN_DAGGER "\xee\xa9\xa5"	// U+ea65
#define ICON_RA_PLAYER "\xee\xa9\xaf"	// U+ea6f
#define ICON_RA_PLAYER_DESPAIR "\xee\xa9\xa6"	// U+ea66
#define ICON_RA_PLAYER_DODGE "\xee\xa9\xa7"	// U+ea67
#define ICON_RA_PLAYER_KING "\xee\xa9\xa8"	// U+ea68
#define ICON_RA_PLAYER_LIFT "\xee\xa9\xa9"	// U+ea69
#define ICON_RA_PLAYER_PAIN "\xee\xa9\xaa"	// U+ea6a
#define ICON_RA_PLAYER_PYROMANIAC "\xee\xa9\xab"	// U+ea6b
#define ICON_RA_PLAYER_SHOT "\xee\xa9\xac"	// U+ea6c
#define ICON_RA_PLAYER_TELEPORT "\xee\xa9\xad"	// U+ea6d
#define ICON_RA_PLAYER_THUNDER_STRUCK "\xee\xa9\xae"	// U+ea6e
#define ICON_RA_PODIUM "\xee\xa9\xb0"	// U+ea70
#define ICON_RA_POISON_CLOUD "\xee\xa9\xb1"	// U+ea71
#define ICON_RA_POTION "\xee\xa9\xb2"	// U+ea72
#define ICON_RA_PYRAMIDS "\xee\xa9\xb3"	// U+ea73
#define ICON_RA_QUEEN_CROWN "\xee\xa9\xb4"	// U+ea74
#define ICON_RA_QUILL_INK "\xee\xa9\xb5"	// U+ea75
#define ICON_RA_RABBIT "\xee\xa9\xb6"	// U+ea76
#define ICON_RA_RADAR_DISH "\xee\xa9\xb7"	// U+ea77
#define ICON_RA_RADIAL_BALANCE "\xee\xa9\xb8"	// U+ea78
#define ICON_RA_RADIOACTIVE "\xee\xa9\xb9"	// U+ea79
#define ICON_RA_RAVEN "\xee\xa9\xba"	// U+ea7a
#define ICON_RA_REACTOR "\xee\xa9\xbb"	// U+ea7b
#define ICON_RA_RECYCLE "\xee\xa9\xbc"	// U+ea7c
#define ICON_RA_REGENERATION "\xee\xa9\xbd"	// U+ea7d
#define ICON_RA_RELIC_BLADE "\xee\xa9\xbe"	// U+ea7e
#define ICON_RA_REPAIR "\xee\xa9\xbf"	// U+ea7f
#define ICON_RA_REVERSE "\xee\xaa\x80"	// U+ea80
#define ICON_RA_REVOLVER "\xee\xaa\x81"	// U+ea81
#define ICON_RA_RIFLE "\xee\xaa\x82"	// U+ea82
#define ICON_RA_RINGING_BELL "\xee\xaa\x83"	// U+ea83
#define ICON_RA_ROAST_CHICKEN "\xee\xaa\x84"	// U+ea84
#define ICON_RA_ROBOT_ARM "\xee\xaa\x85"	// U+ea85
#define ICON_RA_ROUND_BOTTOM_FLASK "\xee\xaa\x86"	// U+ea86
#define ICON_RA_ROUND_SHIELD "\xee\xaa\x87"	// U+ea87
#define ICON_RA_RSS "\xee\xaa\x88"	// U+ea88
#define ICON_RA_RUNE_STONE "\xee\xaa\x89"	// U+ea89
#define ICON_RA_SAGITTARIUS "\xee\xaa\x8a"	// U+ea8a
#define ICON_RA_SAPPHIRE "\xee\xaa\x8b"	// U+ea8b
#define ICON_RA_SATELLITE "\xee\xaa\x8c"	// U+ea8c
#define ICON_RA_SAVE "\xee\xaa\x8d"	// U+ea8d
#define ICON_RA_SCORPIO "\xee\xaa\x8e"	// U+ea8e
#define ICON_RA_SCROLL_UNFURLED "\xee\xaa\x8f"	// U+ea8f
#define ICON_RA_SCYTHE "\xee\xaa\x90"	// U+ea90
#define ICON_RA_SEA_SERPENT "\xee\xaa\x91"	// U+ea91
#define ICON_RA_SEAGULL "\xee\xaa\x92"	// U+ea92
#define ICON_RA_SHARK "\xee\xaa\x93"	// U+ea93
#define ICON_RA_SHEEP "\xee\xaa\x94"	// U+ea94
#define ICON_RA_SHERIFF "\xee\xaa\x95"	// U+ea95
#define ICON_RA_SHIELD "\xee\xaa\x96"	// U+ea96
#define ICON_RA_SHIP_EMBLEM "\xee\xaa\x97"	// U+ea97
#define ICON_RA_SHOE_PRINTS "\xee\xaa\x98"	// U+ea98
#define ICON_RA_SHOT_THROUGH_THE_HEART "\xee\xaa\x99"	// U+ea99
#define ICON_RA_SHOTGUN_SHELL "\xee\xaa\x9a"	// U+ea9a
#define ICON_RA_SHOVEL "\xee\xaa\x9b"	// U+ea9b
#define ICON_RA_SHURIKEN "\xee\xaa\x9c"	// U+ea9c
#define ICON_RA_SICKLE "\xee\xaa\x9d"	// U+ea9d
#define ICON_RA_SIDESWIPE "\xee\xaa\x9e"	// U+ea9e
#define ICON_RA_SITE "\xee\xaa\x9f"	// U+ea9f
#define ICON_RA_SKULL "\xee\xaa\xa1"	// U+eaa1
#define ICON_RA_SKULL_TROPHY "\xee\xaa\xa0"	// U+eaa0
#define ICON_RA_SLASH_RING "\xee\xaa\xa2"	// U+eaa2
#define ICON_RA_SMALL_FIRE "\xee\xaa\xa3"	// U+eaa3
#define ICON_RA_SNAIL "\xee\xaa\xa4"	// U+eaa4
#define ICON_RA_SNAKE "\xee\xaa\xa5"	// U+eaa5
#define ICON_RA_SNORKEL "\xee\xaa\xa6"	// U+eaa6
#define ICON_RA_SNOWFLAKE "\xee\xaa\xa7"	// U+eaa7
#define ICON_RA_SOCCER_BALL "\xee\xaa\xa8"	// U+eaa8
#define ICON_RA_SPADES "\xee\xaa\xaa"	// U+eaaa
#define ICON_RA_SPADES_CARD "\xee\xaa\xa9"	// U+eaa9
#define ICON_RA_SPAWN_NODE "\xee\xaa\xab"	// U+eaab
#define ICON_RA_SPEAR_HEAD "\xee\xaa\xac"	// U+eaac
#define ICON_RA_SPEECH_BUBBLE "\xee\xaa\xad"	// U+eaad
#define ICON_RA_SPEECH_BUBBLES "\xee\xaa\xae"	// U+eaae
#define ICON_RA_SPIDER_FACE "\xee\xaa\xaf"	// U+eaaf
#define ICON_RA_SPIKEBALL "\xee\xaa\xb0"	// U+eab0
#define ICON_RA_SPIKED_MACE "\xee\xaa\xb1"	// U+eab1
#define ICON_RA_SPIKED_TENTACLE "\xee\xaa\xb2"	// U+eab2
#define ICON_RA_SPINNING_SWORD "\xee\xaa\xb3"	// U+eab3
#define ICON_RA_SPIRAL_SHELL "\xee\xaa\xb4"	// U+eab4
#define ICON_RA_SPLASH "\xee\xaa\xb5"	// U+eab5
#define ICON_RA_SPRAY_CAN "\xee\xaa\xb6"	// U+eab6
#define ICON_RA_SPROUT "\xee\xaa\xb8"	// U+eab8
#define ICON_RA_SPROUT_EMBLEM "\xee\xaa\xb7"	// U+eab7
#define ICON_RA_STOPWATCH "\xee\xaa\xb9"	// U+eab9
#define ICON_RA_SUCKERED_TENTACLE "\xee\xaa\xba"	// U+eaba
#define ICON_RA_SUITS "\xee\xaa\xbb"	// U+eabb
#define ICON_RA_SUN "\xee\xaa\xbd"	// U+eabd
#define ICON_RA_SUN_SYMBOL "\xee\xaa\xbc"	// U+eabc
#define ICON_RA_SUNBEAMS "\xee\xaa\xbe"	// U+eabe
#define ICON_RA_SUPER_MUSHROOM "\xee\xaa\xbf"	// U+eabf
#define ICON_RA_SUPERSONIC_ARROW "\xee\xab\x80"	// U+eac0
#define ICON_RA_SURVEILLANCE_CAMERA "\xee\xab\x81"	// U+eac1
#define ICON_RA_SYRINGE "\xee\xab\x82"	// U+eac2
#define ICON_RA_TARGET_ARROWS "\xee\xab\x83"	// U+eac3
#define ICON_RA_TARGET_LASER "\xee\xab\x84"	// U+eac4
#define ICON_RA_TARGETED "\xee\xab\x85"	// U+eac5
#define ICON_RA_TAURUS "\xee\xab\x86"	// U+eac6
#define ICON_RA_TELESCOPE "\xee\xab\x87"	// U+eac7
#define ICON_RA_TENTACLE "\xee\xab\x88"	// U+eac8
#define ICON_RA_TESLA "\xee\xab\x89"	// U+eac9
#define ICON_RA_THORN_ARROW "\xee\xab\x8a"	// U+eaca
#define ICON_RA_THORNY_VINE "\xee\xab\x8b"	// U+eacb
#define ICON_RA_THREE_KEYS "\xee\xab\x8c"	// U+eacc
#define ICON_RA_TIC_TAC_TOE "\xee\xab\x8d"	// U+eacd
#define ICON_RA_TOAST "\xee\xab\x8e"	// U+eace
#define ICON_RA_TOMBSTONE "\xee\xab\x8f"	// U+eacf
#define ICON_RA_TOOTH "\xee\xab\x90"	// U+ead0
#define ICON_RA_TORCH "\xee\xab\x91"	// U+ead1
#define ICON_RA_TOWER "\xee\xab\x92"	// U+ead2
#define ICON_RA_TRAIL "\xee\xab\x93"	// U+ead3
#define ICON_RA_TREFOIL_LILY "\xee\xab\x94"	// U+ead4
#define ICON_RA_TRIDENT "\xee\xab\x95"	// U+ead5
#define ICON_RA_TRIFORCE "\xee\xab\x96"	// U+ead6
#define ICON_RA_TROPHY "\xee\xab\x97"	// U+ead7
#define ICON_RA_TURD "\xee\xab\x98"	// U+ead8
#define ICON_RA_TWO_DRAGONS "\xee\xab\x99"	// U+ead9
#define ICON_RA_TWO_HEARTS "\xee\xab\x9a"	// U+eada
#define ICON_RA_UNCERTAINTY "\xee\xab\x9b"	// U+eadb
#define ICON_RA_UNDERHAND "\xee\xab\x9c"	// U+eadc
#define ICON_RA_UNPLUGGED "\xee\xab\x9d"	// U+eadd
#define ICON_RA_VASE "\xee\xab\x9e"	// U+eade
#define ICON_RA_VENOMOUS_SNAKE "\xee\xab\x9f"	// U+eadf
#define ICON_RA_VEST "\xee\xab\xa0"	// U+eae0
#define ICON_RA_VIAL "\xee\xab\xa1"	// U+eae1
#define ICON_RA_VINE_WHIP "\xee\xab\xa2"	// U+eae2
#define ICON_RA_VIRGO "\xee\xab\xa3"	// U+eae3
#define ICON_RA_WATER_DROP "\xee\xab\xa4"	// U+eae4
#define ICON_RA_WIFI "\xee\xab\xa5"	// U+eae5
#define ICON_RA_WIRELESS_SIGNAL "\xee\xab\xa6"	// U+eae6
#define ICON_RA_WOLF_HEAD "\xee\xab\xa7"	// U+eae7
#define ICON_RA_WOLF_HOWL "\xee\xab\xa8"	// U+eae8
#define ICON_RA_WOODEN_SIGN "\xee\xab\xa9"	// U+eae9
#define ICON_RA_WRENCH "\xee\xab\xaa"	// U+eaea
#define ICON_RA_WYVERN "\xee\xab\xab"	// U+eaeb
#define ICON_RA_X_MARK "\xee\xab\xac"	// U+eaec
#define ICON_RA_ZEBSHIELD "\xee\xab\xad"	// U+eaed
#define ICON_RA_ARCANE_MASK "\xee\xa4\x8c"	// U+e90c
#define ICON_RA_AQUARIUS "\xee\xa4\x8b"	// U+e90b
#define ICON_RA_APPLE "\xee\xa4\x8a"	// U+e90a
#define ICON_RA_ANVIL "\xee\xa4\x89"	// U+e909
#define ICON_RA_ANKH "\xee\xa4\x88"	// U+e908
#define ICON_RA_ANGEL_WINGS "\xee\xa4\x87"	// U+e907
#define ICON_RA_ANCHOR "\xee\xa4\x86"	// U+e906
#define ICON_RA_AMMO_BAG "\xee\xa4\x85"	// U+e905
#define ICON_RA_ALLIGATOR_CLIP "\xee\xa4\x84"	// U+e904
#define ICON_RA_ALL_FOR_ONE "\xee\xa4\x83"	// U+e903
#define ICON_RA_ALIEN_FIRE "\xee\xa4\x82"	// U+e902
#define ICON_RA_ACORN "\xee\xa4\x81"	// U+e901
